/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.Boleto;
import model.Data;
import model.Sorteo;

/**
 *
 * @author Emilio
 */
public class AppLoteria extends javax.swing.JFrame {
    private Data d;
    private ArrayList juego;

    /**
     * Creates new form App
     */
    public AppLoteria() {
        try {
            initComponents();
            d = new Data();
            System.out.println("Conexion exitosa");
            setLocationRelativeTo(this);
            setResizable(false);
            juego=new ArrayList();
            iniciar();
            iniciarConsultaSorteo();
            iniciarConsultaJuego();

        } catch (SQLException ex) {
            System.out.println("Error de conexion: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vntSortear = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblPozoActual = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        txtJuego = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNSorteo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtJugada = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtRutAdmin = new javax.swing.JTextField();
        btnSortear = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        lblConsultarNumero2 = new javax.swing.JLabel();
        lblConsultarNumero3 = new javax.swing.JLabel();
        lblConsultarNumero4 = new javax.swing.JLabel();
        lblConsultarNumero1 = new javax.swing.JLabel();
        txtConsultarSorteo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblConsultar2Aciertos = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblConsultar3Aciertos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblConsultar4Aciertos = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblConsultarGanadores = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblConsultarPremio2Aciertos = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblConsultarPremio3Aciertos = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblConsultarPremio4Aciertos = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblConsultarUltimoPozo = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtRevisarIdJuego = new javax.swing.JTextField();
        btnConsultarJuego = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblRevisarIDSorteo = new javax.swing.JLabel();
        lblRevisarMensaje = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRevisarPremio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lblRevisarNumero1 = new javax.swing.JLabel();
        lblRevisarNumero2 = new javax.swing.JLabel();
        lblRevisarNumero3 = new javax.swing.JLabel();
        lblRevisarNumero4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lblRevisarNumeroSorteo1 = new javax.swing.JLabel();
        lblRevisarNumeroSorteo2 = new javax.swing.JLabel();
        lblRevisarNumeroSorteo3 = new javax.swing.JLabel();
        lblRevisarNumeroSorteo4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miSortear = new javax.swing.JMenuItem();
        miConfiguracion = new javax.swing.JMenuItem();

        javax.swing.GroupLayout vntSortearLayout = new javax.swing.GroupLayout(vntSortear.getContentPane());
        vntSortear.getContentPane().setLayout(vntSortearLayout);
        vntSortearLayout.setHorizontalGroup(
            vntSortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        vntSortearLayout.setVerticalGroup(
            vntSortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyReleased(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pozo"));

        lblPozoActual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPozoActual.setText("$ xxx.xxx.xxx");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPozoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(lblPozoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Juego"));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/1462950578_package_games_card.png"))); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.setEnabled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        txtJuego.setEditable(false);
        txtJuego.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtJuegoComponentAdded(evt);
            }
        });
        txtJuego.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtJuegoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtJuego.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtJuegoInputMethodTextChanged(evt);
            }
        });
        txtJuego.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJuegoKeyTyped(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/1462950173_edit-clear.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Sorteo N°: ");

        lblNSorteo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNSorteo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNSorteo.setText("x");
        lblNSorteo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtJuego, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtJugada, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNSorteo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(txtJugada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorteo"));

        txtRutAdmin.setText("Rut_admin");
        txtRutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutAdminActionPerformed(evt);
            }
        });
        txtRutAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutAdminKeyReleased(evt);
            }
        });

        btnSortear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/1462950424_package_games_board.png"))); // NOI18N
        btnSortear.setText("Sortear");
        btnSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(txtRutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtRutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSortear))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jugar", jPanel8);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Juego"));

        lblConsultarNumero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultarNumero2.setText("1");
        lblConsultarNumero2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConsultarNumero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultarNumero3.setText("1");
        lblConsultarNumero3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConsultarNumero4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultarNumero4.setText("1");
        lblConsultarNumero4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConsultarNumero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultarNumero1.setText("1");
        lblConsultarNumero1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblConsultarNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConsultarNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConsultarNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConsultarNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultarNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultarNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultarNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultarNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtConsultarSorteo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultarSorteoKeyReleased(evt);
            }
        });

        jLabel24.setText("ID Sorteo");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/1462950684_search.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas juego"));

        jLabel9.setText("2 Aciertos");

        lblConsultar2Aciertos.setText("x");

        jLabel11.setText("3 Aciertos");

        lblConsultar3Aciertos.setText("x");

        jLabel13.setText("4 Aciertos");

        lblConsultar4Aciertos.setText("x");

        jLabel23.setText("Ganadores");

        lblConsultarGanadores.setText("x");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel23)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsultar2Aciertos, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblConsultar4Aciertos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addComponent(lblConsultar3Aciertos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblConsultarGanadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblConsultar2Aciertos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultar3Aciertos)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblConsultar4Aciertos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblConsultarGanadores))
                .addContainerGap())
        );

        jLabel15.setText("2 Aciertos");

        lblConsultarPremio2Aciertos.setText("$xxx.xxx");

        jLabel17.setText("3 Aciertos");

        lblConsultarPremio3Aciertos.setText("$xxx.xxx");

        jLabel18.setText("4 Aciertos");

        lblConsultarPremio4Aciertos.setText("$xxx.xxx");

        jLabel21.setText("Ultimo pozo");

        lblConsultarUltimoPozo.setText("$xxx.xxx.xxx");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblConsultarPremio2Aciertos, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(lblConsultarPremio3Aciertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblConsultarPremio4Aciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(lblConsultarUltimoPozo)
                        .addContainerGap())))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblConsultarUltimoPozo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblConsultarPremio2Aciertos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblConsultarPremio3Aciertos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblConsultarPremio4Aciertos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConsultarSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultarSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sorteos Anteriores", jPanel11);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Juego"));

        txtRevisarIdJuego.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRevisarIdJuegoKeyReleased(evt);
            }
        });

        btnConsultarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/1462950684_search.png"))); // NOI18N
        btnConsultarJuego.setText("ConsultarJuego");
        btnConsultarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarJuegoActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Boleto");

        lblRevisarIDSorteo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisarMensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRevisarMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarMensaje.setText("¡Felicidades!");
        lblRevisarMensaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Premio");

        lblRevisarPremio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRevisarPremio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Numeros boleto:");

        lblRevisarNumero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumero1.setText("1");
        lblRevisarNumero1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisarNumero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumero2.setText("1");
        lblRevisarNumero2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisarNumero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumero3.setText("1");
        lblRevisarNumero3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisarNumero4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumero4.setText("1");
        lblRevisarNumero4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(lblRevisarNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevisarNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevisarNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevisarNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblRevisarNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblRevisarNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblRevisarNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblRevisarNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel25.setText("ID Sorteo:");

        lblRevisarNumeroSorteo1.setBackground(new java.awt.Color(255, 255, 255));
        lblRevisarNumeroSorteo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumeroSorteo1.setText("1");
        lblRevisarNumeroSorteo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisarNumeroSorteo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumeroSorteo2.setText("1");
        lblRevisarNumeroSorteo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisarNumeroSorteo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumeroSorteo3.setText("1");
        lblRevisarNumeroSorteo3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisarNumeroSorteo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevisarNumeroSorteo4.setText("1");
        lblRevisarNumeroSorteo4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(lblRevisarNumeroSorteo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevisarNumeroSorteo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevisarNumeroSorteo3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevisarNumeroSorteo4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblRevisarNumeroSorteo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblRevisarNumeroSorteo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblRevisarNumeroSorteo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblRevisarNumeroSorteo4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRevisarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRevisarIDSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRevisarPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConsultarJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(0, 30, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRevisarIdJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRevisarIdJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarJuego)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(lblRevisarIDSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblRevisarPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRevisarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Revisar Juego", jPanel9);

        jMenu1.setText("Archivo");

        miSortear.setText("Sortear");
        miSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSortearActionPerformed(evt);
            }
        });
        jMenu1.add(miSortear);

        miConfiguracion.setText("Configuraciones");
        jMenu1.add(miConfiguracion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearActionPerformed
        try {
            Sorteo sorteo = d.getSorteo(d.getIDUltimoSorteo());
            String rutAdmin = txtRutAdmin.getText();
            if (rutAdmin.equalsIgnoreCase(sorteo.getRut_admin())) {
                d.sortear(sorteo.getId());
                d.actualizarAciertos(sorteo.getId());
                d.actualizarGanadores(sorteo.getId());
                d.actualizarPremiosSorteo(sorteo.getId());
                d.cerrarSorteo(sorteo.getId());
                txtRutAdmin.setText(null);
                JOptionPane.showMessageDialog(this, "Sorteo realizado con exito!");
                iniciar();
            }else if(!rutAdmin.equalsIgnoreCase(sorteo.getRut_admin())){
                JOptionPane.showMessageDialog(this, "Rut administrador invalido. Pruebe nuevamente");
                txtRutAdmin.setText(null);
                txtRutAdmin.requestFocus();
            }
        } catch (SQLException ex) {
            System.out.println("Error para sortear: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSortearActionPerformed

    private void txtRutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutAdminActionPerformed

//    private void agregarJugada(){
////        txtJuego.setText(txtJuego.getText() + numero);
////        btn1.setEnabled(false);
//
//      
//    }
    
    private void btnConsultarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarJuegoActionPerformed
        //Sorteo sorteo; //null
        int idJuego = 0;

        try {
            idJuego = Integer.parseInt(txtRevisarIdJuego.getText());
            if (d.getBoleto(idJuego) instanceof Boleto) {
                Boleto boleto = d.getBoleto(idJuego);
                int idSorteo = boleto.getId_sorteo();
                Sorteo sorteo =d.getSorteo(idSorteo);
                
                if (sorteo.getId() != d.getIDUltimoSorteo()) {
                    lblRevisarIDSorteo.setText(Integer.toString(boleto.getId_sorteo()));

                    String numeros = boleto.getNumeros();
                    String numerosSorteo = sorteo.getNumeros_sorteo();

                    char n1 = numeros.charAt(0);
                    char n2 = numeros.charAt(1);
                    char n3 = numeros.charAt(2);
                    char n4 = numeros.charAt(3);

                    String sn1 = Character.toString(n1);
                    String sn2 = Character.toString(n2);
                    String sn3 = Character.toString(n3);
                    String sn4 = Character.toString(n4);

                    lblRevisarNumero1.setText(sn1);
                    if (getMatch(sn1, numerosSorteo)) {
                        lblRevisarNumero1.setBackground(Color.green);
                    } else if (!getMatch(sn1, numerosSorteo)) {
                        lblRevisarNumero1.setBackground(null);
                    }

                    lblRevisarNumero2.setText(sn2);
                    if (getMatch(sn2, numerosSorteo)) {
                        lblRevisarNumero2.setBackground(Color.green);
                    } else if (!getMatch(sn2, numerosSorteo)) {
                        lblRevisarNumero2.setBackground(null);
                    }

                    lblRevisarNumero3.setText(sn3);
                    if (getMatch(sn3, numerosSorteo)) {
                        lblRevisarNumero3.setBackground(Color.green);
                    } else if (!getMatch(sn3, numerosSorteo)) {
                        lblRevisarNumero3.setBackground(null);
                    }

                    lblRevisarNumero4.setText(sn4);
                    if (getMatch(sn4, numerosSorteo)) {
                        lblRevisarNumero4.setBackground(Color.green);
                    } else if (!getMatch(sn4, numerosSorteo)) {
                        lblRevisarNumero4.setBackground(null);
                    }

                    n1 = numerosSorteo.charAt(0);
                    n2 = numerosSorteo.charAt(1);
                    n3 = numerosSorteo.charAt(2);
                    n4 = numerosSorteo.charAt(3);

                    sn1 = Character.toString(n1);
                    sn2 = Character.toString(n2);
                    sn3 = Character.toString(n3);
                    sn4 = Character.toString(n4);

                    lblRevisarNumeroSorteo1.setText(sn1);
                    lblRevisarNumeroSorteo2.setText(sn2);
                    lblRevisarNumeroSorteo3.setText(sn3);
                    lblRevisarNumeroSorteo4.setText(sn4);

//                lblRevisarAciertos.setText(Integer.toString(boleto.getAciertos()));
                    float aciertos = boleto.getAciertos();
//                Sorteo sorteo = d.getSorteo(boleto.getId_sorteo());
                    float pozo = sorteo.getPozo();
//                float ganadores = sorteo.getTotal_ganadores();
                    //int premioTresAciertos=(int)((0.2*(float)pozo)/(float)tresaciertos)
                    lblRevisarPremio.setText("$" + boleto.getPremio() + "");

                    if (boleto.getPremio() == 0) {
                        lblRevisarMensaje.setText("Siga participando");
                    } else if (boleto.getPremio() > 0) {
                        lblRevisarMensaje.setText("¡Felicitaciones!");
                    } else {
                        lblRevisarMensaje.setText("N/A");
                    }
                } else if(sorteo.getId() == d.getIDUltimoSorteo()){
                    JOptionPane.showMessageDialog(this, "Sorteo aun no se ha sorteado");
                    txtRevisarIdJuego.setText(null);
                    txtRevisarIdJuego.requestFocus();
                }else{
                    juegoinvalido();
                }
            }
        } catch (NumberFormatException e) {
            juegoinvalido();
            JOptionPane.showMessageDialog(this, "Id Juego Invalido");
            iniciarConsultaJuego();
        } catch (SQLException ex) {
            System.out.println("Error al buscar id boleto");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Id juego no realizado");
            iniciarConsultaJuego();
        }

    }//GEN-LAST:event_btnConsultarJuegoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Sorteo sorteo = new Sorteo();
        int idSorteo = 0;

        try {
            String strIdSroteo = txtConsultarSorteo.getText();
            idSorteo = Integer.parseInt(strIdSroteo);

            if (d.getSorteo(idSorteo) instanceof Sorteo) {
                sorteo = d.getSorteo(idSorteo);
                cargarEstadisticaConsulta(sorteo);
            }

        } catch (SQLException ex) {
            System.out.println("Error cargar estadistica" + ex.getMessage());
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ID Sorteo invalido");
            iniciarConsultaSorteo();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtRevisarIdJuegoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRevisarIdJuegoKeyReleased
        String idJuego=txtRevisarIdJuego.getText();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && !idJuego.equalsIgnoreCase("")){
            btnConsultarJuego.doClick();
        }
        
        if(idJuego.length()==0){
            iniciarConsultaJuego();
        }
    }//GEN-LAST:event_txtRevisarIdJuegoKeyReleased

    private void txtConsultarSorteoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarSorteoKeyReleased
        String idSorteo=txtConsultarSorteo.getText();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && !idSorteo.equalsIgnoreCase("")){
            btnConsultar.doClick();
        }
        
        if(idSorteo.length()==0){
            iniciarConsultaSorteo();
        }
    }//GEN-LAST:event_txtConsultarSorteoKeyReleased

    private void jTabbedPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyReleased
//        txtRevisarIdJuego.requestFocus();
    }//GEN-LAST:event_jTabbedPane1KeyReleased

    private void txtRutAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutAdminKeyReleased
        String idRut=txtRutAdmin.getText();
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && !idRut.equalsIgnoreCase("")){
            btnSortear.doClick();
        }
    }//GEN-LAST:event_txtRutAdminKeyReleased

    private void miSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSortearActionPerformed
//        vntSortear.setVisible(true);
    }//GEN-LAST:event_miSortearActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        try {
            Sorteo sorteo = d.getSorteo(d.getIDUltimoSorteo());
//            String juegos = getJuego(juego);
            

            d.registrarBoleto(juego);
            d.actualizarPozo(sorteo.getPozo() + 2000, sorteo.getId());

            mostrarPozo();
//            habilitarJugada();
            limpiar();

            JOptionPane.showMessageDialog(this, "Juego realizado existosamente");
        } catch (SQLException ex) {
            System.out.println("Error al realizar jugada: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void txtJuegoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJuegoKeyTyped

    }//GEN-LAST:event_txtJuegoKeyTyped

    private void txtJuegoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtJuegoInputMethodTextChanged

    }//GEN-LAST:event_txtJuegoInputMethodTextChanged

    private void txtJuegoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtJuegoAncestorAdded

    }//GEN-LAST:event_txtJuegoAncestorAdded

    private void txtJuegoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtJuegoComponentAdded

    }//GEN-LAST:event_txtJuegoComponentAdded

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String numero =txtJugada.getText();
        if(juego.contains(numero)){
            JOptionPane.showMessageDialog(this, "Numero ya ingresado. Pruebe nuevamente");
            txtJugada.setText(null);
            txtJugada.requestFocus();
        }else if(!juego.contains(numero)){
            juego.add(numero);
            setJugada(lbl1,lbl2,lbl3,lbl4);
            txtJugada.setText(null);
            txtJugada.requestFocus();
        }
        
        int largo = juego.size();                
        if (largo == 4) {
            btnJugar.setEnabled(true);
        }else if(largo!=4){
            btnJugar.setEnabled(false);
        }         
    }//GEN-LAST:event_btnAgregarActionPerformed

//    private void validarJugada() {
//        int largo = juego.size();
//
//        if (largo == 4) {
//            btnJugar.setEnabled(true);
//        } else {
//            btnJugar.setEnabled(false);
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String nombre = UIManager.getSystemLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(nombre);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppLoteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AppLoteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AppLoteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AppLoteria.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppLoteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarJuego;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSortear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblConsultar2Aciertos;
    private javax.swing.JLabel lblConsultar3Aciertos;
    private javax.swing.JLabel lblConsultar4Aciertos;
    private javax.swing.JLabel lblConsultarGanadores;
    private javax.swing.JLabel lblConsultarNumero1;
    private javax.swing.JLabel lblConsultarNumero2;
    private javax.swing.JLabel lblConsultarNumero3;
    private javax.swing.JLabel lblConsultarNumero4;
    private javax.swing.JLabel lblConsultarPremio2Aciertos;
    private javax.swing.JLabel lblConsultarPremio3Aciertos;
    private javax.swing.JLabel lblConsultarPremio4Aciertos;
    private javax.swing.JLabel lblConsultarUltimoPozo;
    private javax.swing.JLabel lblNSorteo;
    private javax.swing.JLabel lblPozoActual;
    private javax.swing.JLabel lblRevisarIDSorteo;
    private javax.swing.JLabel lblRevisarMensaje;
    private javax.swing.JLabel lblRevisarNumero1;
    private javax.swing.JLabel lblRevisarNumero2;
    private javax.swing.JLabel lblRevisarNumero3;
    private javax.swing.JLabel lblRevisarNumero4;
    private javax.swing.JLabel lblRevisarNumeroSorteo1;
    private javax.swing.JLabel lblRevisarNumeroSorteo2;
    private javax.swing.JLabel lblRevisarNumeroSorteo3;
    private javax.swing.JLabel lblRevisarNumeroSorteo4;
    private javax.swing.JLabel lblRevisarPremio;
    private javax.swing.JMenuItem miConfiguracion;
    private javax.swing.JMenuItem miSortear;
    private javax.swing.JTextField txtConsultarSorteo;
    private javax.swing.JTextField txtJuego;
    private javax.swing.JTextField txtJugada;
    private javax.swing.JTextField txtRevisarIdJuego;
    private javax.swing.JTextField txtRutAdmin;
    private javax.swing.JDialog vntSortear;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        try {
            Sorteo sorteoActual = d.getSorteo(d.getIDUltimoSorteo());
            int pozo = 0;
            //decidir si crear nuevo sorteo

            if (d.getCantidadSorteos() == 0) { //si es primer sorteo
                d.nuevoSorteo();
                sorteoActual = d.getSorteo(d.getIDUltimoSorteo());
            }

            if (!sorteoActual.isAbierto()) {//si estado de sorteoActual anterior esta cerrado                
//                cargarEstadistica(sorteoActual);

                if (sorteoActual.getTotal_ganadores() == 0) {
                    pozo = sorteoActual.getPozo();
                }

                d.nuevoSorteo();
                sorteoActual = d.getSorteo(d.getIDUltimoSorteo());

                d.actualizarPozo(pozo, sorteoActual.getId());
            }

            int id = sorteoActual.getId();
            lblNSorteo.setText(Integer.toString(id));
            mostrarPozo();
//            cargarEstadistica(d.getSorteo(d.getIDUltimoSorteo() - 1));
            txtRutAdmin.setText(null);
        } catch (SQLException ex) {
            System.out.println("Error iniciar aplicacion" + ex.getMessage());
        }
    }

    private void mostrarPozo() {
        try {
            Sorteo sorteo = d.getSorteo(d.getIDUltimoSorteo());
            //cargarpozo
            int pozo = sorteo.getPozo();

            lblPozoActual.setText("$" + pozo);
        } catch (SQLException ex) {
            System.out.println("Error actualizar pozo: " + ex.getMessage());
        }
    }

//    private void habilitarJugada() {
//        btn1.setEnabled(true);
//    }

    private void limpiar() {
        txtJugada.setText(null);
        juego.clear();        
        limpiarJugada(lbl1,lbl2,lbl3,lbl4);
        btnJugar.setEnabled(false);
        
//        txtJuego.setText(null);
//        btn1.setEnabled(true);
//        btn2.setEnabled(true);
//        btn3.setEnabled(true);
//        btn4.setEnabled(true);
//        btn5.setEnabled(true);
//        btn6.setEnabled(true);
//        btn7.setEnabled(true);
//        btn8.setEnabled(true);
//        btn9.setEnabled(true);
    }

//    private void cargarEstadistica(Sorteo sorteo) {
//        try {
//            int pozo = sorteo.getPozo();
//            lblUltimoPozo.setText("$ " + pozo);
//
//            int ganadores = sorteo.getTotal_ganadores();
//            int dosaciertos = d.getCantidadAciertosSorteo(2, sorteo.getId());
//            int tresaciertos = d.getCantidadAciertosSorteo(3, sorteo.getId());
//            int cuatroaciertos = d.getCantidadAciertosSorteo(4, sorteo.getId());
//            lblGanadores.setText(Integer.toString(ganadores));
//            lbl2aciertos.setText(Integer.toString(dosaciertos));
//            lbl3aciertos.setText(Integer.toString(tresaciertos));
//            lbl4aciertos.setText(Integer.toString(cuatroaciertos));
//
//            //4 aciertos:70%
//            //3 aciertos: 20%
//            //2 aciertos: 10%
//            if (dosaciertos != 0) {
//                int premioDosAciertos = d.getPremio(2, sorteo.getId());
//                lblPozo2Aciertos.setText("$ " + premioDosAciertos + " c/u");
//            } else {
//                lblPozo2Aciertos.setText("$ " + 0 + " c/u");
//            }
//
//            if (tresaciertos != 0) {
//                int premioTresAciertos = d.getPremio(3, sorteo.getId());
//                lblPozo3Aciertos.setText("$ " + premioTresAciertos + " c/u");
//            } else {
//                lblPozo3Aciertos.setText("$ " + 0 + " c/u");
//            }
//
//            if (cuatroaciertos != 0) {
//                int premioCuatroAciertos = d.getPremio(4, sorteo.getId());
//                lblPozo4Aciertos.setText("$ " + premioCuatroAciertos + " c/u");
//            } else {
//                lblPozo4Aciertos.setText("$ " + 0 + " c/u");
//            }
//        } catch (SQLException ex) {
//            System.out.println("Error cargar estadistica " + ex.getMessage());
//        }
//    }

    private void juegoinvalido() {
//        lblRevisarAciertos.setText("N/A");
        lblRevisarNumeroSorteo1.setText("N/A");
        lblRevisarNumeroSorteo2.setText("N/A");
        lblRevisarNumeroSorteo3.setText("N/A");
        lblRevisarNumeroSorteo4.setText("N/A");        
        
        lblRevisarIDSorteo.setText("N/A");
        lblRevisarMensaje.setText("N/A");
        lblRevisarPremio.setText("N/A");
        lblRevisarMensaje.setText("N/A");

        lblRevisarNumero1.setText("N/A");
        lblRevisarNumero2.setText("N/A");
        lblRevisarNumero3.setText("N/A");
        lblRevisarNumero4.setText("N/A");
    }

    private void cargarEstadisticaConsulta(Sorteo sorteo) {
        try {
            if (sorteo.getId() != d.getIDUltimoSorteo()) {
                int pozo = sorteo.getPozo();
                lblConsultarUltimoPozo.setText("$ " + pozo);

                int ganadores = sorteo.getTotal_ganadores();
                int dosaciertos = d.getCantidadAciertosSorteo(2, sorteo.getId());
                int tresaciertos = d.getCantidadAciertosSorteo(3, sorteo.getId());
                int cuatroaciertos = d.getCantidadAciertosSorteo(4, sorteo.getId());
                lblConsultarGanadores.setText(Integer.toString(ganadores));
                lblConsultar2Aciertos.setText(Integer.toString(dosaciertos));
                lblConsultar3Aciertos.setText(Integer.toString(tresaciertos));
                lblConsultar4Aciertos.setText(Integer.toString(cuatroaciertos));

                String numeros = sorteo.getNumeros_sorteo();
                char n1 = numeros.charAt(0);
                char n2 = numeros.charAt(1);
                char n3 = numeros.charAt(2);
                char n4 = numeros.charAt(3);

                String sn1 = Character.toString(n1);
                String sn2 = Character.toString(n2);
                String sn3 = Character.toString(n3);
                String sn4 = Character.toString(n4);

                lblConsultarNumero1.setText(sn1);
                lblConsultarNumero2.setText(sn2);
                lblConsultarNumero3.setText(sn3);
                lblConsultarNumero4.setText(sn4);

                if (dosaciertos != 0) {
                    int premioDosAciertos = d.getPremio(2, sorteo.getId());
                    lblConsultarPremio2Aciertos.setText("$ " + premioDosAciertos + " c/u");
                } else {
                    lblConsultarPremio2Aciertos.setText("$ " + 0 + " c/u");
                }

                if (tresaciertos != 0) {
                    int premioTresAciertos = d.getPremio(3, sorteo.getId());
                    lblConsultarPremio3Aciertos.setText("$ " + premioTresAciertos + " c/u");
                } else {
                    lblConsultarPremio3Aciertos.setText("$ " + 0 + " c/u");
                }

                if (cuatroaciertos != 0) {
                    int premioCuatroAciertos = d.getPremio(4, sorteo.getId());
                    lblConsultarPremio4Aciertos.setText("$ " + premioCuatroAciertos + " c/u");
                } else {
                    lblConsultarPremio4Aciertos.setText("$ " + 0 + " c/u");
                }
            }else if(sorteo.getId() == d.getIDUltimoSorteo()){
                JOptionPane.showMessageDialog(this, "El juego aún no se ha sorteado");
                txtConsultarSorteo.requestFocus();
                iniciarConsultaSorteo();
            }

        } catch (SQLException ex) {
            System.out.println("Error cargar estadistica " + ex.getMessage());
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "ID Sorteo no se ha ralizado");
            iniciarConsultaSorteo();
        }
    }

    private void iniciarConsultaSorteo() {
        txtConsultarSorteo.setText(null);
        txtConsultarSorteo.requestFocus();
        lblConsultar2Aciertos.setText(null);
        lblConsultar3Aciertos.setText(null);
        lblConsultar4Aciertos.setText(null);
        lblConsultarGanadores.setText(null);
        lblConsultarNumero1.setText(null);
        lblConsultarNumero2.setText(null);
        lblConsultarNumero3.setText(null);
        lblConsultarNumero4.setText(null);
        lblConsultarPremio2Aciertos.setText(null);
        lblConsultarPremio3Aciertos.setText(null);
        lblConsultarPremio4Aciertos.setText(null);
        lblConsultarUltimoPozo.setText(null);
    }

    private void iniciarConsultaJuego() {
        
        txtRevisarIdJuego.setText(null);
        txtRevisarIdJuego.requestFocus();
//        lblRevisarAciertos.setText(null);
        lblRevisarNumeroSorteo1.setText(null);
        lblRevisarNumeroSorteo2.setText(null);
        lblRevisarNumeroSorteo3.setText(null);
        lblRevisarNumeroSorteo4.setText(null);
        
        lblRevisarIDSorteo.setText(null);
        lblRevisarMensaje.setText(null);
        lblRevisarNumero1.setText(null);
        lblRevisarNumero1.setBackground(null);
        lblRevisarNumero2.setText(null);
        lblRevisarNumero2.setBackground(null);
        lblRevisarNumero3.setText(null);
        lblRevisarNumero3.setBackground(null);
        lblRevisarNumero4.setText(null);
        lblRevisarNumero4.setBackground(null);
        lblRevisarPremio.setText(null);
    }

    private boolean getMatch(String numero, String numerosSorteo) {
        boolean match=false;
        
        int[] arreglo=new int[4];
        for(int i =0; i<4; i++){
            char c=numerosSorteo.charAt(i);
            String s=String.valueOf(c);
            int n=Integer.parseInt(s);
            arreglo[i]=n;            
        }
        
        for(int n:arreglo){
            String sn=Integer.toString(n);
            if(sn.equalsIgnoreCase(numero)){
                match=true;                
            }
        }
        
        return match;
    }

    private void setJugada(JLabel... lbls) {
        int indice=juego.size()-1;
        Object obnumero=juego.get(indice);
        String strnumero=obnumero.toString();
        int numero=Integer.parseInt(strnumero);
        for(JLabel l: lbls){
            String texto=l.getText();
            if(texto.equalsIgnoreCase("")){
                l.setText(Integer.toString(numero));
                break;
            }
        }
    }

    private void limpiarJugada(JLabel... lbls) {
        for(JLabel l: lbls){
            l.setText("");
        }
    }

//    private String getJuego(ArrayList juego) {
//        StringBuffer numeros=new StringBuffer();
//        String n;
//        for(Object o: juego.toArray()){
//            n=String.valueOf(o);
//            numeros.append(n);
//        }
//        
//        String jugada=numeros.toString();
//       
//        return jugada;
//    }

}
